CREATE TABLE Student(
   ID   INT NOT NULL ,
   NAME VARCHAR(20) NOT NULL,
   AGE  INT NOT NULL,
   PRIMARY KEY (ID)
);

DESC STUDENT;
INSERT INTO STUDENT  VALUES(1,'AMIT',30);
INSERT INTO STUDENT  VALUES(2,'Nira',25);
INSERT INTO STUDENT  VALUES(3,'Tuphan',32);
INSERT INTO STUDENT  VALUES(4,'Nursery',28);
INSERT INTO STUDENT  VALUES(5,'Don',30);


CREATE OR REPLACE PROCEDURE getRecord (in_id IN NUMBER,out_name OUT VARCHAR2,out_age OUT NUMBER)
IS BEGIN
   SELECT name, age
   INTO out_name, out_age
   FROM Student where id = in_id;
END;

